version: '3'

services:
  redis:
    image: 'redis'
    ports:
      - 6379:6379
    expose:
      - 6379
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  web:
    restart: on-failure
    build: ./web
    environment:
    - REDIS_URL=redis://redis:6379
    ports:
      - '81:3000'
    depends_on:
      - redis
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/static:/app/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - web